### ISSUE TITLE
Known issues with the JetBrains 2021.2 update; SOLUTION: Downgrade to 2021.1.3

### ISSUE THREAD

**Issue by SCWells72** [RoseSilverSoftware/IlluminatedCloud#1942]
_Issue created by `RoseSilverSoftware`: 2021-07-27_
_Last updated on Bitbucket: 2024-04-23_

**UPDATE:** I have just released 2.1.8.5 which explicitly blocks installation of Illuminated Cloud 2 into 2021.2. Once the issues have been resolved via 2021.2.* updates and I've verified that IC2 works properly in that release family, I will remove this constraint. If you have already updated to 2021.2, please download and install 2021.1 instead to host IC2.

**UPDATE 2021/8/18:** JetBrains has a 2021.2.1 patch in preview now that seems to resolve at least a few of these issues. I will continue to test with that and, if necessary, subsequent patches to ascertain when it is safe to upgrade to 2021.2.*. Once that is the case, I will publish a new IC2 build that removes the current version constraint and clearly states in the release notes that it's safe to upgrade.

**UPDATE 2021/8/24:** JetBrains has released a 2021.2.1 patch. I will test IC2 with this new release to see whether it has resolved the issues with 2021.2. If so, I will issue a new build this week that allows installation into that version. If not, I will provide an update here about what still remains to be fixed and follow up with JetBrains on those issues.

**UPDATE 2021/9/16:** Sorry I haven't given an update in a while. JetBrains has released 2021.2.2 now and I'm running though testing on it. It looks very similar to 2021.2.1...which is a good thing...except that [IDEA-274533](https://youtrack.jetbrains.com/issue/IDEA-274533) still seemed to occur in 2021.2.1, at least for some people intermittently. I'd really prefer not to open the flood gates knowing that was still an issue. I've followed up (yet again) with my contacts at JetBrains to see if that issue can get some attention. This is by far the longest I've ever kept IC users from moving to the latest-and-greatest from JetBrains, but unfortunately this remaining issue seems completely out of my control since it appears to be with the IDE's plugin classloader. Apologies that this still isn't resolved, but rest assured that I'm committed to getting it done. I'll keep you all posted on further progress.

**UPDATE 2021/9/23:** I just released 2.1.8.9 which finally unlocks IC2 and 2021.2...but with a caveat. As far as I can tell, the `NoClassDefFoundError` issue is still present, at least for some people. I'm continuing to pester JetBrains, but with no proposed resolution timeframe--and the fact that this issue only seems to affect a small set of users--I've decided to move forward with 2021.2 compatibility. If you decide to use 2021.2, please make sure that you're on the latest patch-level, currently 2021.2.2. If you see issues and your install is based on in-place upgrades, please do a full uninstall/reinstall. If you still see issues, please let me know about them and consider moving back to 2021.1.3 as the specific issue that remains is not under my direct control. Having said that, I have implemented a prospective workaround that attempts to force the plugin classloader to load the specific class that seems to be associated with the issue as soon as a project is opened. If that succeeds, hopefully there won't be a downstream issue; if it fails, the user will be informed immediately. Fingers crossed that things go swimmingly from here! If I don't hear about issues over the next few weeks, I'll go ahead and resolve this and deal with any other problems as new issues.

**UPDATE 2021/9/29:** I released 2.1.9.0 which hopefully improves the experience in 2021.2 by squashing some of the noisy errors reported by that host IDE. Hopefully all of the errors from Apache CXF fetching resources via the classloader with a leading slash are gone, and I think I've also eliminated the noise about indeterminate progress indicators that have been emitted into `idea.log` for a while now. I haven't heard anything negative from folks on 2021.2 since last week's release, so I'm hoping that things are going well. I did find and log [another 2021.2 issue](https://youtrack.jetbrains.com/issue/IDEA-279205) with JetBrains that causes focus issues when IC2 generates an unresolvable declaration for the user. Hopefully they'll be able to resolve that in a near-term patch. Otherwise please let me know if you see issues unique to 2021.2 so that I can look into them.

---

If you're having serious issues after upgrading to IntelliJ IDEA/WebStorm/etc. 2021.2, you're not alone. I'm logging this to make it easier for folks to find and track status of known issues with the JetBrains 2021.2 IDE updates. I'll include what I know about so far, though I imagine others will be added to the list.

**NOTE:** If these issues are seriously interfering with your ability to use Illuminated Cloud 2, **please immediately downgrade to the latest build 2021.1** until JetBrains issues at least the first patch for 2021.2. You can download installers for previous builds under the **Other versions** links of the product download pages.

With that preface out of the way, here's what I've seen so far...

**Upgrade failures**

* ["Some conflicts were found in the installation area"](https://youtrack.jetbrains.com/issue/IDEA-274519) - If you see this, just uninstall/reinstall the IDE after the upgrade process terminates.

**Broken IC2 features**

* [Find usages doesn't work propery](#1941) - This seems to be a failed in-place upgrade as well and was resolved for the one reporting user by a scorched earth uninstall/reinstall.
* [Unit test/code coverage issues](https://youtrack.jetbrains.com/issue/IDEA-274516) - There's a breaking plugin SDK change in 2021.2. One workaround is to open coverage explicitly after unit testing completes. Another is to roll back to 2021.1 until 2021.2.1 is released.
* Deploy on save not working - I have a fix for this locally that will be included in the next build.

---

_Comment created by `RoseSilverSoftware`: 2024-04-23_

Removing component: IntelliJ IDEA (automated comment)

---

_Comment created by `RoseSilverSoftware`: 2021-10-11_

Based on positive feedback over the past few weeks, I'm resolving this and removing the startup warning from the product as of 2.1.9.1. If new issues do arise in 2021.2+, please let me know via support email or via a new logged issue in the issue tracker.

---

_Comment created by `RoseSilverSoftware`: 2021-09-23_

Issue #1973 was marked as a duplicate of this issue.

---

_Comment created by `RoseSilverSoftware`: 2021-09-23_

Please see the 2021/9/23 update regarding 2.1.8.9 which unlocks support for 2021.2.

---

_Comment created by `RoseSilverSoftware`: 2021-09-18_

Patrick, if you still have an install handy, could you get it into that state and share your `idea.log` either here or via email? I'd like to see if it's the same thing `NoClassDefFoundError` with `EmbeddedMarkupUtil` or something else. No problem if you don't have access to that install any longer...

---

_Comment created by `patrick_visniewski`: 2021-09-18_

seeing problems with 2021.2.2 :disappointed:

It seems like the syntax checking/etc isn’t working reliably

for example this commented code is still being treated as active code….

and I’ve had a lot of other small issues that add up so I’m still not using 2021.2.2 even

this was not a full uninstall/reinstall of it though, it was after upgrading from 2021.2.1 to 2021.2.2

![](../blob/main/issues/images/3060744501-image.png?raw=true)
I also see all sorts of issues with IDEA losing track of symbols so they start reporting that various items are invalid even though they are perfectly valid and can be deployed without error.

---

_Comment created by `RoseSilverSoftware`: 2021-09-16_

New status update added to pinned post.

---

_Comment created by `RoseSilverSoftware`: 2021-09-08_

Adam, deployment of Aura components via the Tooling API will only deploy the current file, at least assuming it's an update. That allows for much quicker iterative development of the individual pieces of those components. If you prefer that it deploy the entire component bundle each time, you can disable Aura deployment via the Tooling API and, because of how the Metadata API works, the entire bundle will be deployment instead.

---

_Comment created by `veress`: 2021-09-08_

Guys, i’m not sure that it’s a related to this one bug, but i’m using latest Illuminated Cloud 2 and latest IntelliJ IDEA and faced strange issue - when you opening Aura component and checkout to e.g. helper.js or css, do something and then saving it with deployment - Illuminated Cloud submits only html \(cmp\) file to SF. Even with Deploy modified metadata window anyway it’s deploying only cmp file. I should every time go to dev console and copy/paste changes to Aura component and save it in DevConsole instead of deploy because of that. Only me facing this issue and maybe I need to reinstall the stuff or somebody also faced this behavior? Thanks in advance!

---

_Comment created by `rickcapgem`: 2021-09-02_

Very cool. nefarious plans on hold! :slight_smile:

---

_Comment created by `RoseSilverSoftware`: 2021-09-02_

After a full uninstall/reinstall of the IDE, the user who was seeing that issue is no longer seeing it. While that's encouraging, that particular issue wasn't one that reproduced consistently. I've asked him to let me know if it recurs in the next few days. If things still look good on Monday, I'll go ahead and do a new release then. As always, if anyone else using this build with 2021.2.1 is seeing ANY issues that weren't present previously, please let me know so I can investigate them.

---

_Comment created by `rickcapgem`: 2021-09-01_

MY cohorts do not like to hear that.  JetBrains….. get it done! :\)

---

_Comment created by `RoseSilverSoftware`: 2021-09-01_

I've confirmed that one user is still seeing this issue in 2021.2.1 with the attached IC2 build:

https://youtrack.jetbrains.com/issue/IDEA-274533

I've asked that user to do a full uninstall/reinstall of 2021.2.1 to see whether or not the issue is still present in a clean install. I've also reached out to my contacts at JetBrains about this specific issue since it wasn't marked as addressed in 2021.2.1 to see if there's any status on it.

If the problem still occurs in a clean install of 2021.2.1, I will continue to isolate IC2 from that family of JetBrains IDEs until this issue is resolved. I'll provide further status when I have it. Sigh...

---

_Comment created by `rickcapgem`: 2021-09-01_

I will discuss with my cohorts and get back to you… lol but seriously thanks for all the effort and, as usual, great support.

---

_Comment created by `RoseSilverSoftware`: 2021-09-01_

Hah! Those of you using the build posted here are already the inmates running the asylum. What more do you want?!

---

_Comment created by `rickcapgem`: 2021-09-01_

Unlock us! SET US FREEEEEEEE!  :slight_smile:

---

_Comment created by `RoseSilverSoftware`: 2021-09-01_

FYI, it sounds like one person may still be seeing an issue with find usages in 2021.2.1. I'm working with him to see whether it's in fact due to the base IDE or is perhaps some other type of issue that independent of that release. Assuming/hoping that it's the latter, I still plan to post an official build that unlocks 2021.2 tomorrow morning, but if there are still issues then I'll need to report them to JetBrains (again) and keep things the way they are now.

---

_Comment created by `RoseSilverSoftware`: 2021-08-30_

That's definitely not normal behavior, but it also doesn't seem to be 2021.2.*-specific as I see the following proper behavior in 2021.2.1:

![Issue_1944_Aura.png](../blob/main/issues/images/87006688-Issue_1944_Aura.png?raw=true)

Let's treat this separately (for now, at least). Feel free to log a separate issue on this and please attach your `idea.log` from immediately after right-clicking and seeing this behavior.

---

_Comment created by `arnas_io`: 2021-08-30_

I do not know if this is normal behaviour, but now when I right click in aura component file I receive “Nothing here” selection

![](../blob/main/issues/images/3622459896-Screenshot%202021-08-30%20at%2010.18.45.png?raw=true)

---

_Comment created by `RoseSilverSoftware`: 2021-08-27_

Can you [enable debug logging](https://www.illuminatedcloud.com/support/debug-logging) for both unit test execution and code coverage, reproduce the behavior where it doesn't show coverage automatically after **Run with Coverage**, and then send me you `idea.log` for review? To reduce clutter here, you can email it to [support@illuminatedcloud.com](mailto:support@illuminatedcloud.com).

---

_Comment created by `adam-msl`: 2021-08-27_

Scott, I do have the “**Activate Coverage View**” setting enabled.  I’m glad you mentioned this because Code Coverage automatically pops up after running with coverage UNTIL I restart IntelliJ and then I have to select **Run** → **Show Coverage Data** again.

![](../blob/main/issues/images/3667813622-image.png?raw=true)
In summary:  
  
If I select **Run** → **Show Coverage Data**, then Code Coverage shows automatically after running an Apex test via **Run with Coverage** each time I run a test.  
  
Once I restart IntelliJ, I have to select **Run** → **Show Coverage Data** again in order for Code Coverage to show automatically after running an Apex test via **Run with Coverage**.

Let me know if I can provide any more information.  Thanks!

---

_Comment created by `RoseSilverSoftware`: 2021-08-27_

Thanks for the feedback, Adam. If you're not seeing code coverage automatically after running Apex unit tests via **Run with Coverage** _and_ you definitely have the following option enabled:

**Settings / Preferences > Build, Execution, Deployment > Coverage > When new coverage is gathered > Activate Coverage View**

then it's not working properly for you. If that's the case, please let me know the steps you're following so I can look into it.

---

_Comment created by `adam-msl`: 2021-08-27_

I use IntelliJ with IC2 almost every day and recently installed the posted IC2 version to test in 2021.2.\* and have had no issues to date. The only thing I had to do was choose to “Show Coverage Data” again \(**Run** → **Show Coverage Data**\), but that might have been related to how I had set things up on my end. I don’t think it is an issue, but I mentioned it in case someone else looks here and has to do the same. As always, thanks again for an amazing product, Scott!!

![](../blob/main/issues/images/1507639905-image.png?raw=true)

---

_Comment created by `RoseSilverSoftware`: 2021-08-27_

That's great to hear, Rick. Thanks for letting me know. Unless someone does find issues in the next few days, I'll plan on including these changes in next week's official build alongside a few other things.

---

_Comment created by `rickcapgem`: 2021-08-27_

I can report that I have had no issues after 3 days of fairly intense usage.. Usages, Code Coverage.. deploy on save, and most other daily usage has been flawless.

---

_Comment created by `RoseSilverSoftware`: 2021-08-25_

Thanks, Edwin. Certainly good to gather more promising feedback on this.

---

_Comment created by `etomczuk`: 2021-08-25_

Looks working correctly. I did not found any issues \(IntelliJ IDEA 2021.2.1 Ultimate\) - Find Usages, Code Coverage and Deploy on Save works correctly.

---

_Comment created by `RoseSilverSoftware`: 2021-08-25_

That's good to know. Thanks for the quick feedback. Let's give it a solid week or so of burn-in time with a few folks using it as their daily driver and, if everything still holds up, I'll push these same changes into the official build. Anyone else here who wants to add cycles, please feel free to do so and provide additional data points.

---

_Comment created by `WojciechMigas`: 2021-08-25_

It looks like it works correctly. I was playing with it for couple of hours. I’m using 2021.2.1

---

_Comment created by `rickcapgem`: 2021-08-24_

Hi Scott!

I’m in in regard assisting with burn-in . mostly cause I’m just too damn lazy to downgrade and hate moving backward.. lol. I’ll let you know results at the end of the week.

Env Details

![](../blob/main/issues/images/4229792874-image.png?raw=true)

---

_Comment created by `RoseSilverSoftware`: 2021-08-24_

Okay, a brief smoke test of 2021.2.1 actually looks pretty promising. However, this was very much a smoke test and not using the IDE as a full daily driver. I can see that there are numerous watchers on this issue, so if anyone would like to help with some burn-in, it'd be much appreciated.

I'm attaching a build that allows installation into 2021.2* builds of the JetBrains IDEs and includes a few small changes for the plugin SDK changes in those versions. If you want to try it out, I'd recommend that you download and install the 2021.2.1 build of the JetBrains IDE as a secondary install to 2021.1.3 so that, if you do have to move back, it's just a matter of closing 2021.2.1 and starting 2021.1.3. Then download the attached IC2 build (but don't extract it) and install it into 2021.2.1 using **Settings / Preferences > Plugins > Install plugin from disk** (under the gear drop-down menu). Once the IDE restarts, you'll be using this build.

You will likely see some red toaster notifications in the bottom-right with messages like:

```
2021-08-24 11:01:44,325 [  89382]  ERROR - e.plugins.cl.PluginClassLoader - Do not request resource from classloader using path with leading slash 
```

and:

```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
```

The former are pure noise, and I've logged a [request with JetBrains](https://youtrack.jetbrains.com/issue/IDEA-274541) that they be suppressed in some manner. The latter are more legitimate, though IC2 is behaving in the exact same manner that it always has. However, over time JetBrains provides more feedback on how the plugin SDK should be used via messages like this. I will work to move those operations to another thread, but that's a non-trivial change that I'm not jamming into this build.

If you see other issues that impact your actual usage of IC2 in this build with 2021.2.1, please let me know the details here and then feel free to move back to 2021.1.3.

Your time and feedback on this are both greatly appreciated!
